export class CatalogoRoutes {
  static async create(item) {}
}

const itens = [
  {
    nomeItem: "Lápis HB",
    categoria: "Lápis",
    descricao: "Lápis preto para escrita e desenho.",
    imagem: "https://loremflickr.com/400/300/pencil?lock=1",
    estoque: 10,
    temEstoque: true,
  },
  {
    nomeItem: "Lápis de Cor",
    categoria: "Lápis",
    descricao: "Caixa com 12 lápis de cor.",
    imagem: "https://loremflickr.com/400/300/colored-pencils?lock=2",
    estoque: 25,
    temEstoque: true,
  },
  {
    nomeItem: "Caneta Azul",
    categoria: "Canetas",
    descricao: "Caneta esferográfica azul.",
    imagem: "https://loremflickr.com/400/300/blue-pen?lock=3",
    estoque: 30,
    temEstoque: true,
  },
  {
    nomeItem: "Caneta Preta",
    categoria: "Canetas",
    descricao: "Caneta esferográfica preta.",
    imagem: "https://loremflickr.com/400/300/black-pen?lock=4",
    estoque: 0,
    temEstoque: false,
  },
  {
    nomeItem: "Caneta Vermelha",
    categoria: "Canetas",
    descricao: "Caneta esferográfica vermelha.",
    imagem: "https://loremflickr.com/400/300/red-pen?lock=5",
    estoque: 15,
    temEstoque: true,
  },
  {
    nomeItem: "Marca-texto Amarelo",
    categoria: "Marca-textos",
    descricao: "Marca-texto amarelo fluorescente.",
    imagem: "https://loremflickr.com/400/300/yellow-highlighter?lock=6",
    estoque: 8,
    temEstoque: true,
  },
  {
    nomeItem: "Marca-texto Rosa",
    categoria: "Marca-textos",
    descricao: "Marca-texto rosa fluorescente.",
    imagem: "https://loremflickr.com/400/300/pink-highlighter?lock=7",
    estoque: 0,
    temEstoque: false,
  },
  {
    nomeItem: "Borracha Branca",
    categoria: "Borracha",
    descricao: "Borracha branca para lápis.",
    imagem: "https://loremflickr.com/400/300/eraser?lock=8",
    estoque: 20,
    temEstoque: true,
  },
  {
    nomeItem: "Borracha Colorida",
    categoria: "Borracha",
    descricao: "Borracha colorida em formato retangular.",
    imagem: "https://loremflickr.com/400/300/colorful-erasers?lock=9",
    estoque: 12,
    temEstoque: true,
  },
  {
    nomeItem: "Apontador Simples",
    categoria: "Apontadores",
    descricao: "Apontador plástico com uma abertura.",
    imagem: "https://loremflickr.com/400/300/pencil-sharpener?lock=10",
    estoque: 5,
    temEstoque: true,
  },
  {
    nomeItem: "Apontador com Depósito",
    categoria: "Apontadores",
    descricao: "Apontador com reservatório para resíduos.",
    imagem: "https://loremflickr.com/400/300/pencil-sharpener?lock=11",
    estoque: 0,
    temEstoque: false,
  },
  {
    nomeItem: "Caderno Universitário",
    categoria: "Cadernos",
    descricao: "Caderno universitário com 200 folhas.",
    imagem: "https://loremflickr.com/400/300/notebook?lock=12",
    estoque: 18,
    temEstoque: true,
  },
  {
    nomeItem: "Caderno Pequeno",
    categoria: "Cadernos",
    descricao: "Caderno pequeno para anotações.",
    imagem: "https://loremflickr.com/400/300/small-notebook?lock=13",
    estoque: 7,
    temEstoque: true,
  },
  {
    nomeItem: "Caderno de Desenho",
    categoria: "Cadernos",
    descricao: "Caderno com folhas próprias para desenho.",
    imagem: "https://loremflickr.com/400/300/sketchbook?lock=14",
    estoque: 0,
    temEstoque: false,
  },
  {
    nomeItem: "Papel A4",
    categoria: "Papéis",
    descricao: "Pacote de papel sulfite A4 com 500 folhas.",
    imagem: "https://loremflickr.com/400/300/paper?lock=15",
    estoque: 40,
    temEstoque: true,
  },
  {
    nomeItem: "Papel Colorido",
    categoria: "Papéis",
    descricao: "Pacote de folhas coloridas para trabalhos.",
    imagem: "https://loremflickr.com/400/300/colorful-paper?lock=16",
    estoque: 14,
    temEstoque: true,
  },
  {
    nomeItem: "Papel Fotográfico",
    categoria: "Papéis",
    descricao: "Papel fotográfico para impressões.",
    imagem: "https://loremflickr.com/400/300/photo-paper?lock=17",
    estoque: 3,
    temEstoque: true,
  },
  {
    nomeItem: "Cola Branca",
    categoria: "Colas",
    descricao: "Cola branca líquida de 90 gramas.",
    imagem: "https://loremflickr.com/400/300/glue?lock=18",
    estoque: 22,
    temEstoque: true,
  },
  {
    nomeItem: "Cola Bastão",
    categoria: "Colas",
    descricao: "Cola em bastão para papel.",
    imagem: "https://loremflickr.com/400/300/glue-stick?lock=19",
    estoque: 0,
    temEstoque: false,
  },
  {
    nomeItem: "Cola Quente",
    categoria: "Colas",
    descricao: "Bastão de cola quente para pistola.",
    imagem: "https://loremflickr.com/400/300/hot-glue-gun?lock=20",
    estoque: 35,
    temEstoque: true,
  },
  {
    nomeItem: "Tesoura Escolar",
    categoria: "Tesouras",
    descricao: "Tesoura escolar com ponta arredondada.",
    imagem: "https://loremflickr.com/400/300/scissors?lock=21",
    estoque: 9,
    temEstoque: true,
  },
  {
    nomeItem: "Tesoura de Precisão",
    categoria: "Tesouras",
    descricao: "Tesoura pequena para cortes detalhados.",
    imagem: "https://loremflickr.com/400/300/small-scissors?lock=22",
    estoque: 2,
    temEstoque: true,
  },
  {
    nomeItem: "Régua 30cm",
    categoria: "Réguas",
    descricao: "Régua plástica transparente de 30 cm.",
    imagem: "https://loremflickr.com/400/300/ruler?lock=23",
    estoque: 16,
    temEstoque: true,
  },
  {
    nomeItem: "Régua 50cm",
    categoria: "Réguas",
    descricao: "Régua plástica de 50 cm.",
    imagem: "https://loremflickr.com/400/300/ruler?lock=24",
    estoque: 0,
    temEstoque: false,
  },
  {
    nomeItem: "Esquadro 45°",
    categoria: "Esquadros",
    descricao: "Esquadro de 45 graus para desenho técnico.",
    imagem: "https://loremflickr.com/400/300/set-square?lock=25",
    estoque: 6,
    temEstoque: true,
  },
  {
    nomeItem: "Esquadro 60°",
    categoria: "Esquadros",
    descricao: "Esquadro de 60 graus para desenho técnico.",
    imagem: "https://loremflickr.com/400/300/triangle-ruler?lock=26",
    estoque: 4,
    temEstoque: true,
  },
  {
    nomeItem: "Compasso Escolar",
    categoria: "Compassos",
    descricao: "Compasso escolar para desenhos geométricos.",
    imagem: "https://loremflickr.com/400/300/compass-drawing?lock=27",
    estoque: 0,
    temEstoque: false,
  },
  {
    nomeItem: "Calculadora Básica",
    categoria: "Calculadoras",
    descricao: "Calculadora simples de oito dígitos.",
    imagem: "https://loremflickr.com/400/300/calculator?lock=28",
    estoque: 11,
    temEstoque: true,
  },
  {
    nomeItem: "Calculadora Científica",
    categoria: "Calculadoras",
    descricao: "Calculadora científica para cálculos avançados.",
    imagem: "https://loremflickr.com/400/300/scientific-calculator?lock=29",
    estoque: 5,
    temEstoque: true,
  },
  {
    nomeItem: "Grampeador Pequeno",
    categoria: "Grampeadores",
    descricao: "Grampeador manual para uso cotidiano.",
    imagem: "https://loremflickr.com/400/300/stapler?lock=30",
    estoque: 8,
    temEstoque: true,
  },
  {
    nomeItem: "Grampeador Grande",
    categoria: "Grampeadores",
    descricao: "Grampeador reforçado para maior quantidade de folhas.",
    imagem: "https://loremflickr.com/400/300/office-stapler?lock=31",
    estoque: 0,
    temEstoque: false,
  },
  {
    nomeItem: "Grampo 26/6",
    categoria: "Grampos",
    descricao: "Caixa com grampos para grampeador.",
    imagem: "https://loremflickr.com/400/300/staples?lock=32",
    estoque: 50,
    temEstoque: true,
  },
  {
    nomeItem: "Clips Pequeno",
    categoria: "Clips",
    descricao: "Caixa com clips metálicos pequenos.",
    imagem: "https://loremflickr.com/400/300/paper-clips?lock=33",
    estoque: 45,
    temEstoque: true,
  },
  {
    nomeItem: "Clips Grande",
    categoria: "Clips",
    descricao: "Caixa com clips metálicos grandes.",
    imagem: "https://loremflickr.com/400/300/paper-clips?lock=34",
    estoque: 0,
    temEstoque: false,
  },
  {
    nomeItem: "Pasta Plástica",
    categoria: "Pastas",
    descricao: "Pasta plástica para organização de documentos.",
    imagem: "https://loremflickr.com/400/300/plastic-folder?lock=35",
    estoque: 13,
    temEstoque: true,
  },
  {
    nomeItem: "Pasta Suspensa",
    categoria: "Pastas",
    descricao: "Pasta suspensa para arquivos de escritório.",
    imagem: "https://loremflickr.com/400/300/file-folder?lock=36",
    estoque: 6,
    temEstoque: true,
  },
  {
    nomeItem: "Envelope A4",
    categoria: "Envelopes",
    descricao: "Envelope branco para documentos A4.",
    imagem: "https://loremflickr.com/400/300/envelope?lock=37",
    estoque: 28,
    temEstoque: true,
  },
  {
    nomeItem: "Envelope Pequeno",
    categoria: "Envelopes",
    descricao: "Envelope pequeno para correspondências.",
    imagem: "https://loremflickr.com/400/300/envelope?lock=38",
    estoque: 0,
    temEstoque: false,
  },
  {
    nomeItem: "Fita Adesiva",
    categoria: "Fitas",
    descricao: "Fita adesiva transparente para uso geral.",
    imagem: "https://loremflickr.com/400/300/adhesive-tape?lock=39",
    estoque: 19,
    temEstoque: true,
  },
  {
    nomeItem: "Fita Crepe",
    categoria: "Fitas",
    descricao: "Fita crepe para marcações e trabalhos.",
    imagem: "https://loremflickr.com/400/300/masking-tape?lock=40",
    estoque: 10,
    temEstoque: true,
  },
  {
    nomeItem: "Fita Dupla Face",
    categoria: "Fitas",
    descricao: "Fita adesiva dupla face.",
    imagem: "https://loremflickr.com/400/300/double-sided-tape?lock=41",
    estoque: 0,
    temEstoque: false,
  },
  {
    nomeItem: "Limpador de Quadro",
    categoria: "Quadro",
    descricao: "Limpador para quadro branco.",
    imagem: "https://loremflickr.com/400/300/whiteboard-cleaner?lock=42",
    estoque: 4,
    temEstoque: true,
  },
  {
    nomeItem: "Apagador de Quadro",
    categoria: "Quadro",
    descricao: "Apagador para quadro branco.",
    imagem: "https://loremflickr.com/400/300/whiteboard-eraser?lock=43",
    estoque: 9,
    temEstoque: true,
  },
  {
    nomeItem: "Pincel para Quadro",
    categoria: "Quadro",
    descricao: "Pincel marcador para quadro branco.",
    imagem: "https://loremflickr.com/400/300/whiteboard-marker?lock=44",
    estoque: 24,
    temEstoque: true,
  },
  {
    nomeItem: "Pasta Catálogo",
    categoria: "Pastas",
    descricao: "Pasta catálogo com plásticos para documentos.",
    imagem: "https://loremflickr.com/400/300/binder?lock=45",
    estoque: 0,
    temEstoque: false,
  },
  {
    nomeItem: "Organizador de Mesa",
    categoria: "Organizadores",
    descricao: "Organizador plástico para materiais de escritório.",
    imagem: "https://loremflickr.com/400/300/desk-organizer?lock=46",
    estoque: 3,
    temEstoque: true,
  },
  {
    nomeItem: "Porta-canetas",
    categoria: "Organizadores",
    descricao: "Porta-canetas para mesa de trabalho.",
    imagem: "https://loremflickr.com/400/300/pen-holder?lock=47",
    estoque: 7,
    temEstoque: true,
  },
  {
    nomeItem: "Calculadora de Mesa",
    categoria: "Calculadoras",
    descricao: "Calculadora de mesa com visor amplo.",
    imagem: "https://loremflickr.com/400/300/desktop-calculator?lock=48",
    estoque: 0,
    temEstoque: false,
  },
  {
    nomeItem: "Marcador Permanente",
    categoria: "Canetas",
    descricao: "Marcador permanente de ponta média.",
    imagem: "https://loremflickr.com/400/300/permanent-marker?lock=49",
    estoque: 17,
    temEstoque: true,
  },
  {
    nomeItem: "Lapiseira 0.7mm",
    categoria: "Lapiseiras",
    descricao: "Lapiseira com ponta de 0.7 mm.",
    imagem: "https://loremflickr.com/400/300/mechanical-pencil?lock=50",
    estoque: 12,
    temEstoque: true,
  },
  {
    nomeItem: "Grafite 0.7mm",
    categoria: "Grafites",
    descricao: "Tubo de grafite para lapiseira 0.7 mm.",
    imagem: "https://loremflickr.com/400/300/pencil-lead?lock=51",
    estoque: 0,
    temEstoque: false,
  },
];

export function fetchCatalogoPlanilha() {
  return new Promise((resolve, reject) => {
    resolve(itens);
  });
}
