export class CatalogoRoutes {
  static async create(item) {}
}

const itens = [
  {
    nomeItem: "Lápis HB",
    categoria: "Lápis",
    descricao: "Lápis preto para escrita e desenho.",
    imagem: "url",
    estoque: 10,
    temEstoque: true,
  },
  {
    nomeItem: "Lápis de Cor",
    categoria: "Lápis",
    descricao: "Caixa com 12 lápis de cor.",
    imagem: "url",
    estoque: 25,
    temEstoque: true,
  },
  {
    nomeItem: "Caneta Azul",
    categoria: "Canetas",
    descricao: "Caneta esferográfica azul.",
    imagem: "url",
    estoque: 30,
    temEstoque: true,
  },
  {
    nomeItem: "Caneta Preta",
    categoria: "Canetas",
    descricao: "Caneta esferográfica preta.",
    imagem: "url",
    estoque: 0,
    temEstoque: false,
  },
  {
    nomeItem: "Caneta Vermelha",
    categoria: "Canetas",
    descricao: "Caneta esferográfica vermelha.",
    imagem: "url",
    estoque: 15,
    temEstoque: true,
  },
  {
    nomeItem: "Marca-texto Amarelo",
    categoria: "Marca-textos",
    descricao: "Marca-texto amarelo fluorescente.",
    imagem: "url",
    estoque: 8,
    temEstoque: true,
  },
  {
    nomeItem: "Marca-texto Rosa",
    categoria: "Marca-textos",
    descricao: "Marca-texto rosa fluorescente.",
    imagem: "url",
    estoque: 0,
    temEstoque: false,
  },
  {
    nomeItem: "Borracha Branca",
    categoria: "Borracha",
    descricao: "Borracha branca para lápis.",
    imagem: "url",
    estoque: 20,
    temEstoque: true,
  },
  {
    nomeItem: "Borracha Colorida",
    categoria: "Borracha",
    descricao: "Borracha colorida em formato retangular.",
    imagem: "url",
    estoque: 12,
    temEstoque: true,
  },
  {
    nomeItem: "Apontador Simples",
    categoria: "Apontadores",
    descricao: "Apontador plástico com uma abertura.",
    imagem: "url",
    estoque: 5,
    temEstoque: true,
  },
  {
    nomeItem: "Apontador com Depósito",
    categoria: "Apontadores",
    descricao: "Apontador com reservatório para resíduos.",
    imagem: "url",
    estoque: 0,
    temEstoque: false,
  },
  {
    nomeItem: "Caderno Universitário",
    categoria: "Cadernos",
    descricao: "Caderno universitário com 200 folhas.",
    imagem: "url",
    estoque: 18,
    temEstoque: true,
  },
  {
    nomeItem: "Caderno Pequeno",
    categoria: "Cadernos",
    descricao: "Caderno pequeno para anotações.",
    imagem: "url",
    estoque: 7,
    temEstoque: true,
  },
  {
    nomeItem: "Caderno de Desenho",
    categoria: "Cadernos",
    descricao: "Caderno com folhas próprias para desenho.",
    imagem: "url",
    estoque: 0,
    temEstoque: false,
  },
  {
    nomeItem: "Papel A4",
    categoria: "Papéis",
    descricao: "Pacote de papel sulfite A4 com 500 folhas.",
    imagem: "url",
    estoque: 40,
    temEstoque: true,
  },
  {
    nomeItem: "Papel Colorido",
    categoria: "Papéis",
    descricao: "Pacote de folhas coloridas para trabalhos.",
    imagem: "url",
    estoque: 14,
    temEstoque: true,
  },
  {
    nomeItem: "Papel Fotográfico",
    categoria: "Papéis",
    descricao: "Papel fotográfico para impressões.",
    imagem: "url",
    estoque: 3,
    temEstoque: true,
  },
  {
    nomeItem: "Cola Branca",
    categoria: "Colas",
    descricao: "Cola branca líquida de 90 gramas.",
    imagem: "url",
    estoque: 22,
    temEstoque: true,
  },
  {
    nomeItem: "Cola Bastão",
    categoria: "Colas",
    descricao: "Cola em bastão para papel.",
    imagem: "url",
    estoque: 0,
    temEstoque: false,
  },
  {
    nomeItem: "Cola Quente",
    categoria: "Colas",
    descricao: "Bastão de cola quente para pistola.",
    imagem: "url",
    estoque: 35,
    temEstoque: true,
  },
  {
    nomeItem: "Tesoura Escolar",
    categoria: "Tesouras",
    descricao: "Tesoura escolar com ponta arredondada.",
    imagem: "url",
    estoque: 9,
    temEstoque: true,
  },
  {
    nomeItem: "Tesoura de Precisão",
    categoria: "Tesouras",
    descricao: "Tesoura pequena para cortes detalhados.",
    imagem: "url",
    estoque: 2,
    temEstoque: true,
  },
  {
    nomeItem: "Régua 30cm",
    categoria: "Réguas",
    descricao: "Régua plástica transparente de 30 cm.",
    imagem: "url",
    estoque: 16,
    temEstoque: true,
  },
  {
    nomeItem: "Régua 50cm",
    categoria: "Réguas",
    descricao: "Régua plástica de 50 cm.",
    imagem: "url",
    estoque: 0,
    temEstoque: false,
  },
  {
    nomeItem: "Esquadro 45°",
    categoria: "Esquadros",
    descricao: "Esquadro de 45 graus para desenho técnico.",
    imagem: "url",
    estoque: 6,
    temEstoque: true,
  },
  {
    nomeItem: "Esquadro 60°",
    categoria: "Esquadros",
    descricao: "Esquadro de 60 graus para desenho técnico.",
    imagem: "url",
    estoque: 4,
    temEstoque: true,
  },
  {
    nomeItem: "Compasso Escolar",
    categoria: "Compassos",
    descricao: "Compasso escolar para desenhos geométricos.",
    imagem: "url",
    estoque: 0,
    temEstoque: false,
  },
  {
    nomeItem: "Calculadora Básica",
    categoria: "Calculadoras",
    descricao: "Calculadora simples de oito dígitos.",
    imagem: "url",
    estoque: 11,
    temEstoque: true,
  },
  {
    nomeItem: "Calculadora Científica",
    categoria: "Calculadoras",
    descricao: "Calculadora científica para cálculos avançados.",
    imagem: "url",
    estoque: 5,
    temEstoque: true,
  },
  {
    nomeItem: "Grampeador Pequeno",
    categoria: "Grampeadores",
    descricao: "Grampeador manual para uso cotidiano.",
    imagem: "url",
    estoque: 8,
    temEstoque: true,
  },
  {
    nomeItem: "Grampeador Grande",
    categoria: "Grampeadores",
    descricao: "Grampeador reforçado para maior quantidade de folhas.",
    imagem: "url",
    estoque: 0,
    temEstoque: false,
  },
  {
    nomeItem: "Grampo 26/6",
    categoria: "Grampos",
    descricao: "Caixa com grampos para grampeador.",
    imagem: "url",
    estoque: 50,
    temEstoque: true,
  },
  {
    nomeItem: "Clips Pequeno",
    categoria: "Clips",
    descricao: "Caixa com clips metálicos pequenos.",
    imagem: "url",
    estoque: 45,
    temEstoque: true,
  },
  {
    nomeItem: "Clips Grande",
    categoria: "Clips",
    descricao: "Caixa com clips metálicos grandes.",
    imagem: "url",
    estoque: 0,
    temEstoque: false,
  },
  {
    nomeItem: "Pasta Plástica",
    categoria: "Pastas",
    descricao: "Pasta plástica para organização de documentos.",
    imagem: "url",
    estoque: 13,
    temEstoque: true,
  },
  {
    nomeItem: "Pasta Suspensa",
    categoria: "Pastas",
    descricao: "Pasta suspensa para arquivos de escritório.",
    imagem: "url",
    estoque: 6,
    temEstoque: true,
  },
  {
    nomeItem: "Envelope A4",
    categoria: "Envelopes",
    descricao: "Envelope branco para documentos A4.",
    imagem: "url",
    estoque: 28,
    temEstoque: true,
  },
  {
    nomeItem: "Envelope Pequeno",
    categoria: "Envelopes",
    descricao: "Envelope pequeno para correspondências.",
    imagem: "url",
    estoque: 0,
    temEstoque: false,
  },
  {
    nomeItem: "Fita Adesiva",
    categoria: "Fitas",
    descricao: "Fita adesiva transparente para uso geral.",
    imagem: "url",
    estoque: 19,
    temEstoque: true,
  },
  {
    nomeItem: "Fita Crepe",
    categoria: "Fitas",
    descricao: "Fita crepe para marcações e trabalhos.",
    imagem: "url",
    estoque: 10,
    temEstoque: true,
  },
  {
    nomeItem: "Fita Dupla Face",
    categoria: "Fitas",
    descricao: "Fita adesiva dupla face.",
    imagem: "url",
    estoque: 0,
    temEstoque: false,
  },
  {
    nomeItem: "Limpador de Quadro",
    categoria: "Quadro",
    descricao: "Limpador para quadro branco.",
    imagem: "url",
    estoque: 4,
    temEstoque: true,
  },
  {
    nomeItem: "Apagador de Quadro",
    categoria: "Quadro",
    descricao: "Apagador para quadro branco.",
    imagem: "url",
    estoque: 9,
    temEstoque: true,
  },
  {
    nomeItem: "Pincel para Quadro",
    categoria: "Quadro",
    descricao: "Pincel marcador para quadro branco.",
    imagem: "url",
    estoque: 24,
    temEstoque: true,
  },
  {
    nomeItem: "Pasta Catálogo",
    categoria: "Pastas",
    descricao: "Pasta catálogo com plásticos para documentos.",
    imagem: "url",
    estoque: 0,
    temEstoque: false,
  },
  {
    nomeItem: "Organizador de Mesa",
    categoria: "Organizadores",
    descricao: "Organizador plástico para materiais de escritório.",
    imagem: "url",
    estoque: 3,
    temEstoque: true,
  },
  {
    nomeItem: "Porta-canetas",
    categoria: "Organizadores",
    descricao: "Porta-canetas para mesa de trabalho.",
    imagem: "url",
    estoque: 7,
    temEstoque: true,
  },
  {
    nomeItem: "Calculadora de Mesa",
    categoria: "Calculadoras",
    descricao: "Calculadora de mesa com visor amplo.",
    imagem: "url",
    estoque: 0,
    temEstoque: false,
  },
  {
    nomeItem: "Marcador Permanente",
    categoria: "Canetas",
    descricao: "Marcador permanente de ponta média.",
    imagem: "url",
    estoque: 17,
    temEstoque: true,
  },
  {
    nomeItem: "Lapiseira 0.7mm",
    categoria: "Lapiseiras",
    descricao: "Lapiseira com ponta de 0.7 mm.",
    imagem: "url",
    estoque: 12,
    temEstoque: true,
  },
  {
    nomeItem: "Grafite 0.7mm",
    categoria: "Grafites",
    descricao: "Tubo de grafite para lapiseira 0.7 mm.",
    imagem: "url",
    estoque: 0,
    temEstoque: false,
  },
];

export function fetchCatalogoPlanilha() {
  return new Promise((resolve, reject) => {
    resolve(itens);
  });
}
